#!/bin/bash
# A git commit-msg hook to enforce commit message conventions.
#
# This script checks if the commit message follows the conventional format:
# <type>: <subject>
# Types:    feat, fix, docs, style, refactor, test, chore
# Subject:  should be a brief description of the change.
#
# If the commit message does not follow the format, the commit is aborted
# and an error message is displayed.
#
# To install this hook, save this script as .git/hooks/commit-msg
# and make it executable: chmod +x .git/hooks/commit-msg
#
# Usage: This hook is automatically invoked by Git during the commit process.
# The commit message file path is passed as the first argument.
# Exit Codes:
# 0 - Commit message is valid
# 1 - Commit message is invalid
#

COMMIT_MESSAGE_FILENAME="$1"
COMMIT_MESSAGE_HEADER=$(head -n 1 "${COMMIT_MESSAGE_FILENAME}")
COMMIT_MESSAGE_PATTERN="^(feat|fix|infra|docs|style|refactor|test|chore): .{4,}$"

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
BRANCH_NAME_PATTERN="^([^/]+/)*(feat|fix|infra|docs|style|refactor|test|chore)/.{4,}"

echo ""
echo "[Git Hook] - [commit-msg]:"
echo ""

# Validate branch name
if [[ ! "${BRANCH_NAME}" =~ $BRANCH_NAME_PATTERN ]]; then
    echo "[ERROR] - Branch name does not follow the conventional format."
    echo ""
    exit 1
fi

# Validate commit message
if [[ ! "${COMMIT_MESSAGE_HEADER}" =~ $COMMIT_MESSAGE_PATTERN ]]; then
    echo "[ERROR] - Commit message does not follow the conventional format."
    echo "[INFO] Expected format: <type>: <subject>"
    echo "[INFO] Allowed types: feat, fix, docs, style, refactor, test, chore"
    echo "[INFO] Subject should be brief (min 5 characters)."
    echo "[INFO] Example valid commit message: feat: add new feature"
    echo ""
    exit 1
fi

echo "[SUCCESS] - Commit message is valid."
echo ""

exit 0
